# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Oksana Ketova"
description: "Portfolio and other works by Oksana Ketova"
author:      "Oksana Ketova"
